# ENV
config_name: "frozen_lake_8_8_2.yaml"
is_slippery: False

# TRAINING
n_episodes: 10000
n_steps: 100
exploration_ratio: 0.7
learning_rate: 0.9
discount_factor: 0.9
e_decay_limit: 0.05
e_decay_rate: 0.01

# MISC
render: False
report_file: False
