# ENV
config_name: "taxi_2.yaml"

# TRAINING
n_episodes: 10000
n_steps: 100
exploration_ratio: 0.5
learning_rate: 0.9
discount_factor: 0.1
e_decay_limit: 0.05
e_decay_rate: 0.01

# MISC
render: False
report_file: False
