# ENV
config_name: "taxi_1.yaml"

# TRAINING
n_episodes: 20000
n_steps: 100
exploration_ratio: 0.1
learning_rate: 0.1
discount_factor: 0.6
e_decay_limit: 0.05
e_decay_rate: 0.01

# MISC
render: False
report_file: False
